# Generated by Django 3.2.5 on 2021-07-05 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last Name')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teacher_profiles', verbose_name='Profile Picture')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+111-222-333-444'.", regex='\\+?[\\d]{3}-[\\d]{3}-[\\d]{3}-[\\d]{3}')], verbose_name='Phone Number')),
                ('room_number', models.CharField(max_length=8, verbose_name='Room Number')),
                ('subjects', models.ManyToManyField(related_name='Teachers', related_query_name='teachers', to='directory.Subject', verbose_name='Subjects')),
            ],
        ),
    ]
